# Your GitHub workflow file under .github/workflows/
name: Documentation CI

on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: | 
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - name: Check current directory
        run: |
            pwd
            ls -la
      - name: Build
        run: | 
            cd ./docs
            make html     

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
